name: badstomach
channels:
  - bioconda
dependencies:
  - python=3.6
  - biopython
  - matplotlib
  - pandas
  - scikit-learn
  - xgboost
  - sra-tools
<<<<<<< HEAD
=======
  - pip:
    - srapy
  - scikit-plot
  - 
>>>>>>> origin/master

