---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "PrIMP - Prediction of Infection-prone Microbiome Pathways"
keywords:    "PrIMP, Metagenomics, Microbiome, Qiime, Pathways"
description: "A python- and R-based toolkit for the predictive analysis of infection-prone microbiome pathways"
source_link: "https://github.com/NCBI-Hackathons/PrIMP"
favicon:     "img/favicon.png"
touch_icon:  "img/touch_icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#29aeb9'
  green:     '#22C676'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  red:       '#d9534f'
  grey:      '#343434'

kramdown:
  auto_ids:  false

